### ISSUE TITLE
Quesition: How change to Token TTL?

### ISSUE THREAD

**Issue by alexandrst88** [coreos/dex#1004]
it there way to change token ttl or make ttl very long like half an year? Thanks

**Comment by ericchiang** [comment]
The default TTL is 24 hours. Configuration is part of the config https://github.com/coreos/dex/blob/0e0b4c53ef86a8795a6647ac47fac2855f1ad91e/examples/config-dev.yaml#L31-L34

Half a year? Ummmmm please don't do that. You should really look into refresh tokens if you want long lived access like that.

Closing since there's no bug.

**Comment by alexandrst88** [comment]
Thanks!
