### ISSUE TITLE
Use access_token for API access?

### ISSUE THREAD

**Issue by furuholm** [coreos/dex#1054]
Some time ago Auth0 switched from using ID tokens to using access tokens for accessing API:s from clients [1][2]. Is this something that you consider doing as well? 

Background: I'm developing an API that uses Auth0 but am considering supporting Dex as well for certain scenarios. That's why I'm looking for differences between the two products.

[1] Auth0 docs: Introducing OIDC Conformant Authentication/Calling APIs with Access Tokens - https://auth0.com/docs/api-auth/intro#calling-apis-with-access-tokens

[2] Auth0 docs: Why you should always use access tokens to secure an API - https://auth0.com/docs/api-auth/why-use-access-tokens-to-secure-apis

**Comment by ericchiang** [comment]
Dex is currently un-opinionated about access_tokens (they're currently random values) because it doesn't have a traditional OAuth2 API that can return information about user. We'll have to implement an access_token for the user_info endpoint https://github.com/coreos/dex/issues/376 at some point though.

What would you actually want to use an access_token for?

**Comment by furuholm** [comment]
I am using the token to authorize access to my API server (through implicit grant flow in my React web client).

I can get around this by passing the ID token from my web app instead, so I am not in a pressing need for this. But as the Auth0 article states, they recommend ID tokens to be used for client authentication and access tokens for API authorization (the Compare tokens section [1] shows this quite nicely). So it's more that I spotted a difference that seemed important rather than not being able to use dex.

It may also be that I have got this all wrong and e.g. missed that there is an API in dev for validating access tokens? In that case I will have to apologise for trolling the issue tracker with my ignorance 😄 

[1] https://auth0.com/docs/api-auth/why-use-access-tokens-to-secure-apis#compare-tokens

**Comment by ericchiang** [comment]
> API server 

Just to be sure, you mean Kubernetes API server?

Auth0's article is specific to Auth0's service, not OpenID Connect and Kubernetes. Since Auth0's access_token is specific to Auth0 (as they state it's supposed to be opaque to the client), Kubernetes wouldn't be able to understand the access_token anyway.

There are probably subtler points, but I don't think that recommendation applies to talking to the Kubernetes API server, which only accepts ID tokens.

**Comment by furuholm** [comment]
Sorry for not being clear on this. The API that I mentioned is part of a service that we develop. So it is not a Kubenetes API server.

**Comment by furuholm** [comment]
Auth0 says the access_token should be opaque the client, but it's not opaque to an API that uses the access_token for authentication.

Either way. I'm closing this as I am satisfied with your response.
