### ISSUE TITLE
Github organisations are case-insensitive

### ISSUE THREAD

**Issue by devonbarrett** [coreos/dex#1095]
Github organisations are case-insensitive, but the `teamsForOrg` check is not. This led to a hard to track error where the user was being show as in the org, but no teams were being returned.

E.g. https://api.github.com/orgs/CoReOS

**Comment by ericchiang** [comment]
There's still a canonical spelling of an org. E.g. https://api.github.com/orgs/CoReOS returns

```
{
  "login": "coreos",
}
```

I'd really rather not do case conversions. It's a pain with emails and other systems that interpret the id_token claims aren't guaranteed to respect case-insensitive comparisons.

This should be fixed with a better error message and/or documentation.

**Comment by ericchiang** [comment]
Going to close this since we want to support the canonical spelling and not do fuzzy matching.

**Comment by fivovic** [comment]
If at all possible, can we get a warning message thrown when the org name used in the dex config for a github connector does not match the case of the login name as presented by the github api?

I know it is niche, but this exact issue happened to me this week within argocd. Someone changed the case of our org name without notice, and it was very time-consuming to troubleshoot and track down why group permissions were broken when dex was simply outputting nothing but a successful login with no groups attached to the user.

Or at least the github connector document page can be updated to describe this interaction?

**Comment by nabokihms** [comment]
@fivovic could you please open a separate issue for your case? This one is about slightly different case and was closed 5 years ago.
