### ISSUE TITLE
Support MongoDB Database

### ISSUE THREAD

**Issue by dalu** [coreos/dex#115]
So far dex apparently supports pgsql, in-memory.
I'd like to help out (also for my own benefit) and make it support mongodb via the gopkg.in/mgo driver.

However it seems like pgsql is hardcoded and dex isn't storage-agnostic.

**Comment by bobbyrullo** [comment]
@dalu - we'd love for dex to support more storage backends. Yes, pgsql is more or less hardcoded right now, so that would need to change, but that was due to expedience rather than any desire for pgsql to be the One True RDBMS backend.

So, if you do go down the route of adding mongo DB support, you'd have to unhardcode pgsql somehow. However it _most_ of the pgsql code is still applicable to other SQL backends, so ideally it would be done in a way that allows SQL backends to share code somehow, while allowing for the existence of other types of backends (eg Mongo).

FYI, @bcwaldon is going to make an etcd backend at some point, so might be worth chatting with him

**Comment by dalu** [comment]
Hmm I think I'll wait and see what @bcwaldon comes up with and then make adjustments.
Too many cooks :)

Something like
```go
type StorageInterface {
    Type() string
    Init() error
    Config() storage.Config
    MigrateAll() error
    UserRepo() user.UserRepo
    ClientIdentityRepo() client.ClientIdentityRepo
    //...
}
```

I think I remember a package that would abstract most common databases, I'll search around

**Comment by bobbyrullo** [comment]
I wasn't suggesting try to share too much code between Mongo and Postgres implementations, I was thinking more between (for example) Postgres and MySQL implementations.

As for your storage interface - yeah something like that sounds about right - right now we're pretending that you can have a UserRepo and a ClientIDRepo from two different backends, but that doesn't really work, so it would be better just to have one thing which wraps them all up. Would reduce the the number of things the Server object has to keep track of as well.

**Comment by bcwaldon** [comment]
@dalu for now, I don't think we can reasonably support more than one backend. If the demand for a backend other than postgresql grows, or if we feel differently about our ability to support multiple backends, we will definitely consider mongodb.
