### ISSUE TITLE
connectors: LDAP

### ISSUE THREAD

**Issue by rektide** [coreos/dex#119]
Being able to proxy requests to a LDAP is useful.
I would love an even semi-working implementation.

This feature was [mentioned in the announcement](https://coreos.com/blog/announcing-dex/).

**Comment by sym3tri** [comment]
Yes! This is something we're very interested in doing, but no work has begun on this feature yet. If you can add more details about what sort of integration features you'd like that would be helpful for whoever picks this up.

**Comment by philhug** [comment]
here's a list of configuration options needed for a read-only connector, without group support:
* connection string or server/port/ssl (ldaps://ldapserver:389)
* basedn
* searchdn / searchpass (DN used to search user)
* searchbase (where to search for users)
* searchfilter, e.g. (&(objectClass=person)(mail=?))

for password change we might need:
* passwordhashmethod (SHA)

if registration should be supported, it gets more complicated because the whole LDAP object needs to be created, which includes construction of the DN and all attributes.

**Comment by philips** [comment]
The first step here would be for someone to provide an example configuration of openldap with some users and groups. That would give someone less familiar with ldap a starting point.

**Comment by fnordahl** [comment]
I have a LDAP Connector in the works. It is not quite ready yet, but I would really like initial feedback/reviews nontheless.

Please have a look at #178

**Comment by philips** [comment]
@fnordahl Nice! I would love to have an example kubernetes setup with openldap that we could test against too.

**Comment by fnordahl** [comment]
@philips I have linked to a openldap Docker image that may be usefull and wrote some notes in a comment on the PR. Let me know if there is anything else I can provide/help with.
