### ISSUE TITLE
Running on GKE

### ISSUE THREAD

**Issue by joshkurz** [coreos/dex#1268]
Will it ever be possible to run Dex on GKE? I know you have to run the api server with certain configurations, but are there any discussions related to making this work in a hosted k8s environment such as GKE or EKS?

**Comment by jimangel** [comment]
No, unfortunately all managed k8s providers control the master / control plane so you cannot modify the OIDC params. As far as I know the only way to implement Dex with a cloud provider would be if you have shell access to the api servers.

I believe the thought process is that you do not need dex / OIDC auth if you're using a cloud provider since you could use their IAM solution for permissions / access.

/close

**Comment by joshkurz** [comment]
Thanks, was just wondering if you guys knew of any special magic that I wasn't aware of.
