### ISSUE TITLE
feature request: automatically login oidc accounts from registration page

### ISSUE THREAD

**Issue by sym3tri** [coreos/dex#166]
Currently if a user registers with a Google account, then goes back to the site and tries to _register_ again with the same account they get a vague error message. Instead we should just log them in b/c they almost certainly meant to click "login" instead of "register".

**Comment by joeatwork** [comment]
+1 - let's drop the whole magic register/login thing and just let the user explicitly choose?

**Comment by bobbyrullo** [comment]
+1 to the fix, -1 the dropping the magic. +1 to adding *more* mag :)

What I mean is: It's still useful to have a link to a registration page. But it can be smarter about what happens when someone comes in with an existing account.

FWIW we already have "just let the user explicitly choose" - there's a reg link on login page and vice versa; this bug is asking for more than that.

**Comment by ericchiang** [comment]
![screenshot from 2015-12-18 15-47-31](https://cloud.githubusercontent.com/assets/2342749/11909651/ac1d4688-a59e-11e5-95ab-16f43d34e9f6.png)
