### ISSUE TITLE
Feature: Allow invites to work for not just local connector.

### ISSUE THREAD

**Issue by silas** [coreos/dex#201]
Invitations emails currently don't seem to support the oidc connector.

**Steps**
- enable only oidc connector
- disable registration
- send invitation email

**What happens**

The invitation email redirects me to a page that asks me to enter a new password.

**What I expect to happen**

Some type of oidc flow.

**Comment by joeatwork** [comment]
I think this might be as designed. That is, the invitation email link

1) verifies your email address when you click it, and then
2) bounces you to a "Set a password" page, and then
3) directs you to someplace in the client app (as configured by the client app)

Is that what you're experiencing?

**Comment by silas** [comment]
The user couldn't login after going through the flow. Prompting the user for a password doesn't really make sense when the local connector isn't enabled.

The entry added to `remote_identity_mapping` had a blank `connector_id` field, so I don't think ti would ever work.

**Comment by joeatwork** [comment]
Aaaaah. Got it.

**Comment by joeatwork** [comment]
Ok, talked with @bobbyrullo  - this is actually a missing feature/design in dex - that being "How do we bless individual external oidc users"

**Comment by bobbyrullo** [comment]
given that, can you rename this issue or close this issue and make a new one?

**Comment by bobbyrullo** [comment]
The way this should work is that when an invite happens, there's no remote connector added (right now the local one is added) and when someone comes in with a remote identity with that email, it merges them.

**Comment by rsoletob** [comment]
I'm working in this issue and I have some questions about this. 

Is a connector ID needed in the create user method inside User's API? If it is, a special claim could be sent to the target email for processing request to retrieve remote ID using the connector authetication flow. Otherwise if the connector ID isn't present in the request, Could the user choose the connector to authenticate?

In the issue #184 there is a suggestion about split `CreateUser` method and `SendInviteEmail`. I agree with this approach but the question is: How do split this methods, two endpoints for the User's API?

**Comment by ericchiang** [comment]
> Is a connector ID needed in the create user method inside User's API? If it is, a special claim could be sent to the target email for processing request to retrieve remote ID using the connector authetication flow. Otherwise if the connector ID isn't present in the request, Could the user choose the connector to authenticate?

Yes, is sounds reasonable to put that information in the token sent in the email.

> In the issue #184 there is a suggestion about split CreateUser method and SendInviteEmail. I agree with this approach but the question is: How do split this methods, two endpoints for the User's API?

The suggestion wasn't to create two APIs, it's to address an flaw in the current setup is. When you create a user the following things happen:

1. Create a user with a temporary password.
2. Send invite email.
3. User follows the link in the email (with a token) and changes their password.

If you try to do that twice, the current API will error on step 1 saying you've already created that user so you can't resend the email. The proposal in #184 was to create a user without a "remote identity" then provide some logic around that (see [this comment](https://github.com/coreos/dex/issues/184#issuecomment-168230616)).

However, it might be even more reasonable for the invite to not create the user. So something like this.

1. Send invite email
2. User follows the link, logs in through some connector (local or remote).
3. Create a user with a remote identity.

**Comment by bobbyrullo** [comment]
> However, it might be even more reasonable for the invite to not create the user. 

That's a reasonable approach, had we done it that way from the start. But given that invites *do* create the user now, and a lot of code expects that, what advantage does this change give that makes it worth all the re-tooling?

**Comment by joeatwork** [comment]
(Discussed this a bit with @ericchiang  offline, summarizing here) - I've got an app which uses Dex for authentication, and presents a list of "invitations issued for which haven't been executed". Right now, I'm using "email verified" to mean "invited but haven't responded". While it would break my assumptions a little bit, in the medium term showing "tokens issued for whom users have not been created" would be just as good, if not a bit better (and the change in my app to accomodate the change in Dex wouldn't be too crazy)

**Comment by rsoletob** [comment]
We discovered some problems when End-User is returned to client callback with a valid code to request an Access Token after registration/invitation.

- `state` and `nonce`: According to [OIDC](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest), this parameters are recommended to mitigate Cross-Site Request Forgery and replay attacks. These params would be generated by the client.
- `scopes`: Each client could request its own scopes, so DEX can't create default scopes for them.

These problems are related to client so the solution could be a processing by the client. This approach solves the problem:
- Client has a main page redirect uri when there isn't a Authorization code and redirect uri callbacks when there is it.
- When End-User clicks on the link, it is redirected to verify email or accept invitation endpoint where request is validated.
- If End-User is verified, it is redirected to the client's main page without Authorization code. (Maybe a DEX page showing info like "User has been verified, you will be redirected in 5 seconds" would be recommended)
- End-User could authenticate on DEX throught Authorization code flow using its client.

However this approach has a problem with the connector ID, where an attacker could use other OIDC registered in DEX that uses same email for an End-User that it isn't verified yet.
This problem is weird I think but it's possible. 

To solve this issue and allow invites to work for others connector we can use a special claim with the connector ID inside email verification token. So when an End-User is created (API or self-registration) DEX would create an user with not verified email and a new entry in remote_identity_mapping table with the connector ID setted in special claim, user DEX identifier, user DEX identifier as remote identifier and a boolean `false` in a new column with name `validated` or `assigned` for example. When user log in the system using connector, DEX would check this table and if End-User uses correct connector DEX will update remote_identity_mapping values with correct remote identifier from IDP and `true` value in the new column created.

What do you think about this approach?

**Comment by ericchiang** [comment]
@rsoletob Sorry, I think I'm missing what the exact issue / attack is, and from what I can gather this seems like it'd be better suited for it's own issue. I'm particularly having trouble parsing this sentence:

> However this approach has a problem with the connector ID, where an attacker could use other OIDC registered in DEX that uses same email for an End-User that it isn't verified yet.

At what point in dex's email verification flow is there an issue? Does the email in the JWT not have a nonce? Does redirect URL after verifying an email provide something incorrect?

Can you please open a new issue with 1) what you're doing 2) what you expect dex to produce 3) what actions dex actually took.

**Comment by rsoletob** [comment]
I'll try to explain this better.

> At what point in dex's email verification flow is there an issue? Does the email in the JWT not have a nonce? Does redirect URL after verifying an email provide something incorrect?

I just opened issue #300 to explain and propose a solution for this problem.

> @rsoletob Sorry, I think I'm missing what the exact issue / attack is, and from what I can gather this seems like it'd be better suited for it's own issue. I'm particularly having trouble parsing this sentence:
> 
> However this approach has a problem with the connector ID, where an attacker could use other OIDC registered in DEX that uses same email for an End-User that it isn't verified yet.

Imagine you have registered two OIDC connectors like Google and Facebook. When you create an User using API you don't select which connector will be used. Nowadays, DEX does not provide other connector different than local, but if we use the @bobbyrullo's suggestion

> The way this should work is that when an invite happens, there's no remote connector added (right now the local one is added) and when someone comes in with a remote identity with that email, it merges them.

, this attack could happen:

- Admin creates an User using API and DEX send mail to it.
- User has a Gmail and Facebook account with same email.
- Facebook account is compromised by an attacker.
- User click on the link inside DEX mail invitation and according to #300 is redirected to client's main page.
- The attacker could use Facebook account to log in with the same privileges than user.

Therefore I suggest this when issue #300 is solved:

Restrict the connectors that users could be mapped to during the invite/verify email process.
In order to implement this, DEX could use a special claim with the connector ID inside email verification/invitation token. So when an End-User is created (API or self-registration), DEX would create an user with not verified email and a new entry in remote_identity_mapping table with next values:

- the connector ID set in special claim as connector_id.
- user DEX identifier as user_id.
- user DEX identifier as remote identifier.
- boolean false in a new column with name validated or assigned for example.

When user log in the system using a connector, DEX would check this table and if End-User uses correct connector DEX will update remote_identity_mapping table values with correct remote identifier from IDP and true value in the new column created.

**Comment by ericchiang** [comment]
> this attack could happen:

> * Admin creates an User using API and DEX send mail to it.
> * User has a Gmail and Facebook account with same email.
> * Facebook account is compromised by an attacker.
> * User click on the link inside DEX mail invitation and according to #300 is redirected to client's main page.
> * The attacker could use Facebook account to log in with the same privileges than user.

In this scenario the steps would go as follows:

1. User receives link with JWT in Gmail which allows them to login.
2. User follows links with JWT, is presented with login options for Gmail (ok) and Facebook (compromised)
3. User logs in through Gmail.
4. dex confirms that the account matches the email in the JWT, creates user and remote identity.

At this point the database would look something like this:

```
Users
ID     | email            | email verified 
-------------------------------------------
foobar | foobar@gmail.com | true

Remote Identities
User ID | Client ID | Remote ID
-------------------------------------
foobar  | gmail     | {{ GMAIL ID }}
```

Notice that there's is nothing connecting the Facebook account. All future actions should not allow you to access the dex user without logging into the Gmail account.

dex must be aware of this when doing things like merging accounts, but I think this design prevents compromise for remote accounts with emails that happen to match the one registered by dex.

**Comment by bobbyrullo** [comment]
```
Restrict the connectors that users could be mapped to during the invite/verify email process.
In order to implement this, DEX could use a special claim with the connector ID inside email verification/invitation token.
```

This makes sense to me.

```
 So when an End-User is created (API or self-registration), DEX would create an user with not verified email and a new entry in remote_identity_mapping table with next values:

the connector ID set in special claim as connector_id.
user DEX identifier as user_id.
user DEX identifier as remote identifier.
boolean false in a new column with name validated or assigned for example.
```

Since we now would know the connector from the claim in the email, why not wait until the user clicks the email to add the remote identity? That way we don't have to add a new column. (not that a new column is bad, but having another enabled/disabled flag makes one more thing we have to worry about when checking the validity of the user, which means something that could we could forget to do...)

**Comment by rsoletob** [comment]
> Since we now would know the connector from the claim in the email, why not wait until the user clicks the email to add the remote identity? That way we don't have to add a new column. (not that a new column is bad, but having another enabled/disabled flag makes one more thing we have to worry about when checking the validity of the user, which means something that could we could forget to do...)

Yes, I agree with you, it's annoying to take care of new column values and logic. We are going to look for a new solution for this without new column.

**Comment by ericchiang** [comment]
Dex doesn't do invites anymore and we don't plan to add this feature back in. Closing.
