### ISSUE TITLE
EmailVerification link should take you to redirectURL with valid access token

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#229]

**Comment by rsoletob** [comment]
The same problem exist with the User's API when you create a user using `CreateUser` method and send the email invitation. When the user clicks on the link and inserts its new credentials it's redirected to client's callback URL without valid Authorization code. The code in [server/password.go](https://github.com/coreos/dex/blob/master/server/password.go#L232-L266) show the problem in method `ChangePassword` which retrieves the callback URL:

```go
	plaintext := r.r.FormValue("password")
	cbURL, err := r.h.um.ChangePassword(r.pwReset, plaintext)
	....
	if cbURL == nil {
		r.data.Success = true
		execTemplate(r.w, r.h.tpl, r.data)
		return
	}

	http.Redirect(r.w, r.r, cbURL.String(), http.StatusSeeOther)

```

Could the same solution fix both issues?

**Comment by bobbyrullo** [comment]
yes, I think it would be the same solution.

**Comment by rsoletob** [comment]
Hey there @bobbyrullo, our proposal is redirect user when it clicks on the email link to a place where client could do some OIDC flow, not give a valid authorization code throught email link.

> I'm sure I'm missing something, but how is this different than the http://coreos.com/invitation/callback? claim?

This claim fit prefectly with our proposal, so when user is created, for example, client puts into request its main page to redirect, in example-app would be http://127.0.0.1. Therefore email link has main page URI, so if dex checks this redirect URI is valid, client would have this redirect URI registered in dex (client would has registered two redirect URIs: http://127.0.0.1/ and http://127.0.0.1/callback).

> Are you trying to make it so that someone can log-in with the link in the emails?

Yes, we were trying it, [here](https://github.com/Tecsisa/dex/commit/62ff648e56b765da1000392881b3e9ca184f8077) is the proposal using only http://127.0.0.1/callback (it needs improve error messages).

However, we prefer redirect user to main page (http://127.0.0.1/) instead of callback URI (http://127.0.0.1/callback).

What do you think about this?

**Comment by ericchiang** [comment]
Dex no longer has SMTP settings.
