### ISSUE TITLE
Add ability to set connectors through bootstrapping API

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#360]
This is another feature that now goes through the --db-url flag. See #298.

**Comment by ericchiang** [comment]
As discussed with @bobbyrullo this is going to be difficult because connectors use arbitrary JSON which our generated API client does not support.

Maybe make an exception for this case and don't worry about the generated client?

**Comment by ericchiang** [comment]
From OOB conversations, there is an `any` type we can use to do this.

https://developers.google.com/discovery/v1/type-format#type-and-format-summary

**Comment by ecordell** [comment]
Something that might make this a little simpler:

Instead of a single endpoint that varies based on the `type` field of the connector, why not have per-type endpoints? e.g. `/connector/ldap` and `/connector/local`. This would make it easy to define schemas for each separate type and do the appropriate validations, etc.

**Comment by ericchiang** [comment]
I don't think there's anything that prevents us from having multiple connectors of a particular type. E.g. multiple `ldap`s so we'd have to figure out how to express that. Might not be as simple as just having one endpoint that takes a list :)
