### ISSUE TITLE
How to create an Admin User and Client

### ISSUE THREAD

**Issue by TelanJ** [coreos/dex#367]
Hi! I'm parsing dex and now developing my own app. I am trying to GET the list of the users registered in the client. I have read a few discussions in the issues and found out that I need to have Admin access in both User and Client.

**Comment by miguelcubillo** [comment]
Hi, 
In order to create an admin user you have to make a POST request authenticating with the overlord secret to the admin endpoint (see https://github.com/coreos/dex/tree/master/schema/adminschema). And as for clients, i'm afraid the only way to promote a client to admin is by using SQL.(there is an Issue opened to address this https://github.com/coreos/dex/issues/327)

**Comment by ericchiang** [comment]
@TelanJ please refer to @miguelcubillo's comment. Closing this issue.
