### ISSUE TITLE
LDAP Connector: don't read TLS assets from disk

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#382]
The LDAP Connector currently requires TLS assets. However, writing files to disk is problematic for containerized deployments where dex workers expect to pull their entire state from the database.

Consider adding a `caFileBytes` field to the LDAP connector which takes a base64 encoded TLS certificate.

cc @fnordahl

**Comment by bobbyrullo** [comment]
Seems ok - we'll allow for both right?

**Comment by ericchiang** [comment]
Yep. No depreciation of existing fields.

**Comment by chancez** [comment]
Going to :-1:. This would probably reduce overall security by providing another access method to what is effectively the keys to the kingdom. TLS Assets are considered sensitive, and are similar in sensitivity to passwords, which we hash in the DB for security. Having them stored in the DB unencrypted is not good, and encrypting them in the DB is counter-productive as it would mean you need an encryption key on disk, making storing the TLS assets in the DB moot.

I don't see any reason TLS assets shouldn't simply remain a file on disk you must pull in. 

I think containers argument does not make a lot of sense, you simply need a way to get the files on the host your container is running, this is not really any different than a situation without containers. It's up to config management, or orchestration tooling to make these files available on the host so the process can access them. 

Your original comment says that worker's expect to pull **state** from the DB, I do not consider TLS assets/configuration state, they're configuration values, and having configuration in the DB often is not the correct answer.

I know you closed a similar issue, but I wanted to voice my general thought that configuration vary rarely belongs in the DB. This is often an anti-pattern and should generally be avoided. Just because configuration files/env vars _can_ be painful, doesn't mean they _need_ to be painful.

**Comment by ericchiang** [comment]
> I know you closed a similar issue, but I wanted to voice my general thought that configuration vary rarely belongs in the DB. This is often an anti-pattern and should generally be avoided. Just because configuration files/env vars can be painful, doesn't mean they need to be painful.

DB vs files for configuration is a high point of contention ATM because dex can be configured by pulling info from the db, from config files, and from command line flags. Additionally, the connectors configs already contain sensitive data (client id and secrets) which are sitting in the DB un-encrypted.

I do like the idea of dex using a single configuration file for connectors, secrets, and email. This would drastically simplify dex's config and eliminate the need to add a ton of things to the bootstrapping API.

**Comment by bobbyrullo** [comment]
@chancez damn, you're right - I forgot that this connector would be loaded into the database, I thought it would just be a file that gets mounted in. Yeah, we don't want these secrets in the DB.

**Comment by sym3tri** [comment]
+1 to not storing in the DB

Also agree that app config in the DB is not good. However we need a separate discussion on what is actually app config and what is app data.

**Comment by ericchiang** [comment]
I'd like to note that the current LDAP connector stores the `searchBindPw` field plain text in the db :smile: 

Anyway moving this conversation to #377
