### ISSUE TITLE
Timeline for removed features

### ISSUE THREAD

**Issue by lgleim** [coreos/dex#710]
Hi, is there a timeline for readding the features removed in v2? Namely
1. Registration flows.
2. Local user management.
3. SMTP configuration and email verification.
4. Several of the login connectors that have yet to be ported.

I'm basically trying to determine whether to use v1 or v2 for an upcoming project.

**Comment by ericchiang** [comment]
We track upcoming releases and goal using GitHub milestones[0], but I can comment on the specific points:

> 1. Registration flows.

Dex will likely add link that redirects you to a different site which performs registration (https://github.com/coreos/dex/issues/548). That app could then grab user information then make the API call to register a user. Depends on us tracking users (propoal here [1]) so we can block users who aren't registered.

We hope to add another example project, like the `example-app` but provider-side, as a starting point for how the other app could work.

No concrete timeline on this.

> 2. Local user management.

These primitives already exist in the API[2] (see methods involving "Passwords").

> 3. SMTP configuration and email verification.

Unlikely to be added back into v2. Outside apps should handle sending emails, verifying them, and registering users based off that info.

> 4. Several of the login connectors that have yet to be ported.

Is there one you're looking for specifically? Hard to comment on the timeline.

> I'm basically trying to determine whether to use v1 or v2 for an upcoming project.

While v2 is missing features, there are technical reasons we favored a rewrite (some of them are enumerated here: [3]). Basically, many features in v1 are in a half working state (you can't send an email invite for a non-local user), or hard to work with (authenticating against the API) and that's why we removed them. For those reasons I can't really recommend using v1.

[0] https://github.com/coreos/dex/milestones
[1] https://github.com/coreos/dex/blob/master/Documentation/proposals/user-object.md
[2] https://github.com/coreos/dex/blob/master/api/api.proto
[3] https://github.com/coreos/dex/blob/master/Documentation/v2.md

**Comment by ericchiang** [comment]
Going to close this because there's not really an actionable issue. Can you open more focused issues for features you'd like added back into dex v2?

In future the dex-dev mailing list[0] is a better place for questions and general discussion.

[0] https://groups.google.com/forum/#!forum/dex-dev

**Comment by lgleim** [comment]
Thanks for the feedback. I will create focused issues later today.
