### ISSUE TITLE
Documentation: Administration

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#73]
- [ ] authctl
- [ ] misc Worker flags
- [ ] Key rotation
- [ ] User Administration API

**Comment by stongo** [comment]
bump - especially User Administration API

**Comment by adrianlop** [comment]
Hello, we are studying Dex because we have an inhouse solution auth server, and we'd like to adopt Dex if suits well with our needs.

In the meantime, we're currently documenting Dex a bit, because we need to clarify the coverage of the app, and we started documenting the API (we already documented users API, and we want to doc all APIs).

We're willing to do PRs to the project (not only doc, go code too).

This is a sample proposal for the API docs. We'd enclose everything using MarkDown, like the files you have in /Documentation.

Do you like it this way? Please comment:
```
Description: Enable/disable a user
Usage:
  Headers:
    Authorization: Bearer token* (this token is obtained once you've auth yourself)
POST api/v1/users/:id/disable
    body : {"Disable" : false}
    response: {
      "ok": true
    }
```

**Comment by ericchiang** [comment]
@adrianlop we currently working on adding a swagger definition of the API with generated static HTML docs. Should be done today or tomorrow. Does this work for you?

**Comment by ericchiang** [comment]
@adrianlop please see #285. We still need to increase the amount of documentation in our [schema definitions](https://github.com/coreos/dex/blob/26fa124efd6a8f19885f620030bd6193140b1c69/schema/workerschema/v1.json), but this is the initial attempt to generate documentation.

**Comment by adrianlop** [comment]
@ericchiang yes, it's ok for us too. great job, thanks!

**Comment by ericchiang** [comment]
Since none of the features mentioned in the top comment exist in v2 I'm going to close this. New API docs here: https://github.com/coreos/dex/blob/master/Documentation/api.md
