### ISSUE TITLE
Documentation: explain how to write an app that uses dex

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#755]
Brought up by @set321go in #753

This can include:
* App that wants to talk to the Kubernetes API on behalf of a user.
* App that uses OpenID Connect to authenticate a user (it does its own authz).
* App that uses a proxy headers to authenticate a user going through an OpenID Connect aware proxy.
* Putting an app that doesn't do authentication or authorization behind an OpenID Connect aware proxy.

p1 because this kind of documentation is a blocker for users who want to use dex.

**Comment by freefood89** [comment]
hello @ericchiang 

I am new here and would like to look into contributing to docs first, but I need some clarification on this issue:

1. How many examples do you need? I was thinking of starting off with express + passport, and maybe flask as well.
2. Which OpenID Connect aware proxy were you hoping to get covered? I've never used an OIDC proxy before so I would like to try it out. I found [UNINETT/goidc-proxy](https://github.com/UNINETT/goidc-proxy) but I don't like it because it has no releases

**Comment by ericchiang** [comment]
@freefood89 we're going to be rolling a OpenID Connect proxy ourselves. If you want to try express+passport we'd be super happy to include it in our examples. It also helps us test our implementation.

**Comment by freefood89** [comment]
@ericchiang feel free to assign the issue to me if you can

**Comment by ericchiang** [comment]
@freefood89 I don't think I can (your outside the org). There's a lot to this issue anyway, so I don't think it's a big deal.

Please reach out if you need any help or find any issues.

I remember one of the frameworks requiring parts of the spec we don't implement. You may want to look at https://github.com/coreos/dex/issues/376 for background.

**Comment by freefood89** [comment]
Looks like the only working express app I know that uses Dex consumes a hacked passport module called oidc-passport, which I know is not a supported module because it's written by a friend. I'm contemplating writing a passport module myself, but for now I will look into making an example using flask first.

**Comment by ericchiang** [comment]
@freefood89 there's a proposal for adding the userinfo endpoint in that issue https://github.com/coreos/dex/issues/376#issuecomment-271725208. If you want to give it a crack, feel free.

**Comment by akshatprakash** [comment]
we need an identity provider for our app. we need all the features which were removed in v2. namely

1. Registration flows.
2. Local user management.
3. SMTP configuration and email verification.
4. Several of the login connectors that have yet to be ported.

is there a way to implement these in go, so that when you guys are done with adding them back into v2, i can easily just update dex api and these features get handled by dex instead of our custom code?

i reckon yall will be adding these features using the gRPC api..

**Comment by ericchiang** [comment]
> Registration flows.
> Local user management.
> SMTP configuration and email verification.

@akshatprakash we don't have plans to add those features back in. Dex isn't a user management system, so these are more appropriate for orthogonal apps that want to talk to dex's gRPC API or use it's login flows. E.g. for the registration flows, we would probably add a link to our login screen that send the user to a different app that handles registration.

**Comment by SEJeff** [comment]
@akshatprakash perhaps [CoreOS's fork ](https://github.com/coreos/oauth2_proxy) of [bit.ly's oauth2 proxy](https://github.com/bitly/oauth2_proxy) will do what you want?

**Comment by SEJeff** [comment]
@ericchiang also, could you common on [your PR on bitly's oauth2_proxy](https://github.com/bitly/oauth2_proxy/pull/389)? Seems like they're relatively close to merging it with a small bit of love. Seems worth doing.

**Comment by ericchiang** [comment]
@SEJeff PR updated. Know anyone at bitly to help it get merged? :)
