### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by theobouwman** [coreos/dex#806]
Hello,

I want to build Dex into my next project. It's going to be an API for a rental company where users should login using Facebook, Google or even more providers later on.

I can run Dex by ./bin/dex serve examples/config-dev.yaml but what's next? How can I let the user authenticate using Facebook or Google?

Thanks in advance.

**Comment by rithujohn191** [comment]
Hi,

Dex v2 does not support Facebook logins yet. We would need to add custom logic to enable this feature. 

You can use OpenID Connect to enable Google logins. You would need to specific an OIDC connector in the Dex ConfigMap as detailed here: https://github.com/coreos/dex/blob/master/examples/config-dev.yaml#L55-L63. In order to use the OIDC connector you must register dex as an OIDC client with Google.

**Comment by theobouwman** [comment]
Thanks, I'll try

**Comment by theobouwman** [comment]
Should I use Go-IODC package ?

**Comment by ericchiang** [comment]
Mind if we move this to dex-dev? There's not really an issue here and improving the getting started experience is covered by #755
