### ISSUE TITLE
RBAC user field is Base64 encoded

### ISSUE THREAD

**Issue by blakebarnett** [coreos/dex#942]
Dex v2.4.1 w/LDAP connector
K8s v1.6.2

Here's an example RBAC DENY entry:
`I0510 22:55:45.410874       6 rbac.go:87] RBAC DENY: user "https://dex.url#CjZDTj1CbGFrZSBCYXJuZXR0LE9VPVVzZXJzLE9VPVBvc3RtYXRlcyxEQz1hZCxEQz1vZmZpY2USBGxkYXA" groups [vpn-prod dept-engineering vpn-stage team-infra system:authenticated] cannot "list" resource "pods" cluster-wide`

Is there any way to have Dex provide a non-encoded entry for the user field?

**Comment by andybrucenet** [comment]
In case anyone else comes to this problem (which I also have):
`echo '[base-64-id] | base64 --decode -i - | perl -pe 's/([\x00-\x20\\]+)/ /g' | awk '{print $1}'`

That at least gives me the user ID. The format of the base64-encoded variable is kinda unexpected; there is:
`[LF][Ctrl+F]user-id[Ctrl+R][Ctrl+Q][connector-id]`

As an example:
`echo 'CgZhYnJ1Y2USEWxkYXBfaGxzZGV2X2xvY2Fs' | base64 --decode -i -`

Returns:
```
00000000: 0a06 6162 7275 6365 1211 6c64 6170 5f68  ..abruce..ldap_h
00000010: 6c73 6465 765f 6c6f 6361 6c              lsdev_local
```

However, a slightly longer user ID:
`echo 'CgphY2hlYW1pdHJ1EhFsZGFwX2hsc2Rldl9sb2NhbA' | base64 --decode -i -`

Returns:
```
00000000: 0a0a 6163 6865 616d 6974 7275 1211 6c64  ..acheamitru..ld
00000010: 6170 5f68 6c73 6465 765f 6c6f 6361       ap_hlsdev_loca
```

Note that the connector ID is truncated. I suspect there is a maximum length for base64-encoded variable? But I haven't reviewed the source to discover this.

**Comment by ericchiang** [comment]
dup of https://github.com/coreos/dex/issues/892

**Comment by rithujohn191** [comment]
@andybrucenet ,

> The format of the base64-encoded variable is kinda unexpected; there is: [LF][Length]user-id[Ctrl+R][Length][connector-id]

We use this particular format because a combination of the Connector ID and UserID (https://github.com/coreos/dex/blob/master/server/oauth2.go#L269-L274) returned by the connector are used for unique identification. I will go ahead and add some documentation to clarify this.

@blakebarnett ,
Would the solution proposed in https://github.com/coreos/dex/issues/892#issuecomment-293973008 be suitable for you? If so I'll close out this issue as a dup.

**Comment by ericchiang** [comment]
Closing as a dup
