### ISSUE TITLE
Authentication issues when user is a memberof large set of groups

### ISSUE THREAD

**Issue by alekssaul** [coreos/dex#958]
Seeing issues where dex is not able to authenticate the user into tectonic-console when the user is a member of large number of groups. 
Came across the issue while troubleshooting a customer cluster and can reproduce it in my lab against Active Directory 2008. For me the tip over point seem to be around 158 groups that the user is a member of.

Tectonic-console shows 
```
2017/05/30 18:14:54 server: no token found: token cookie not found in request: http: named cookie not present
```
tectonic-lb shows 
```
::ffff:192.168.1.4 - [::ffff:192.168.1.4] - - [30/May/2017:18:17:41 +0000] "GET /favicon.ico HTTP/1.1" 200 1000 "https://cluster.alekssaul.lab/identity/auth?client_id=tectonic-console&redirect_uri=https%3A%2F%2Fcluster.alekssaul.lab%2Fauth%2Fcallback&response_type=code&scope=openid+email+profile+groups+audience%3Aserver%3Aclient_id%3Atectonic-console+audience%3Aserver%3Aclient_id%3Atectonic-kubectl&state=" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" 709 0.105 [tectonic-system-tectonic-console-80] 10.2.1.20:80 2163 0.105 200"
```

**Comment by ericchiang** [comment]
This is going to be hard to change without modifying how the Kubernetes API server talks to dex. For what it's worth I wrote up some thoughts about this here:

https://docs.google.com/document/d/1uMBo9dkQozaZn25NzsL_bklONCzLPtXeXIhteD2t_dE/edit#heading=h.42fbd5ovbir

Since that proposal is a big change, I don't foresee us being able to take immediate action on this. Maybe we can error out sooner when the groups list is too large, and document workarounds.

**Comment by ericchiang** [comment]
As an intermediate step, we should error out if the number of groups is too large.

**Comment by lypht** [comment]
Since #988 is closed, I wanted to update the steps we've had to take to allow some groups to authenticate with github, and others through email.  Some of our teams are rather large; updating the tectonic-identity config map manually would have been too time consuming.  I wrote the following quick hack to iterate through a list of emails in a file (i.e., users.txt) and generate the yaml necessary to copy and paste into the configmap.  The only prerequisite is a node package `@rbtdev/node-cmd-bcrypt` as the coreOS bcrypt-tool cannot operate unattended.  It can be installed with `npm install -g @rbtdev/node-cmd-bcrypt`.
```
#!/bin/bash

# This script creates the manual user entries for teams too large for the tectonic identity github webhook to paginate properly.

file=pw.txt

if [ -f $file ] ; then
    rm $file
fi

while IFS='' read -r line || [[ -n "$line" ]]; do
    echo "- email: \"$line\""
    PASSWORD=$(openssl rand -base64 36)
    echo "$PASSWORD" >> pw.txt
    echo "  hash: \"$(passwdjs hash -r 12 $PASSWORD)\""
    echo "  username: \"$line\""
    UUID=$(uuidgen)
    echo "  userID: \"$UUID\""
done < "$1"

paste -ds "$1" pw.txt | sed 's/.com/.com /g' | sed 's/ s/ /g'
```
If your input email addresses don't have a `.com` suffix, modify your sed replacement accordingly.

For large teams, dumping the output to a file is helpful.  Make it executable, and run `userGen.sh users.txt > team.txt` (assuming you've named the script `userGen.sh`).
Then step though the remaining manual user creation instructions [here](https://coreos.com/tectonic/docs/latest/admin/user-management.html).

Note, this has only been tested on Darwin.  I hope this is helpful for others.

**Comment by chartono** [comment]
We run into this situation too.  LDAP was working for some of us within same AD groups.  Thanks to this bug analysis that pointed out large group.  My work around was to add additional filter in the LDAP Group Search.  For example for our AD group setup (used in the Cluster Role Binding Subject Name):
- ADTeamXX-Admin
- ADTeamXX-ReadOnly

LDAP Group Info:
          groupSearch:
            filter: (objectClass=group)(CN=ADTeamXX*)
This way the returned group is only those that we really use in Tectonic RBAC.

**Comment by rithujohn191** [comment]
@chartono could you specify which version of Dex you are using?

**Comment by justaugustus** [comment]
@rithujohn191 we're on `quay.io/coreos/dex:v2.5.0`
I can provide any additional details you need! :)
cc: @chartono

**Comment by rithujohn191** [comment]
to re-iterate this was an issue with the way the tectonic-console was handling its cookies...it has been fixed here: https://github.com/coreos-inc/bridge/pull/1637

Dex does not put any hard limit on the number of user groups.

Closing out this issue since it has been fixed in tectonic and is not an issue with the way Dex handles groups.

**Comment by r0fls** [comment]
Is there a related github issue in tecetonic? We're experiencing this and it would be helpful if this issue linked to a solution.
