### ISSUE TITLE
warning for bcrypt hashing cost

### ISSUE THREAD

**Issue by colhom** [coreos/dex#962]
This refers to bcrypt hashes provided for static password login via the local connector.

Bcrypt password hashes generated with too many rounds can cause the `auth/local` call to take many seconds, an even timeout. As of now, there's no indication as to what the reason for the timeout is.

It would be nice if dex detected and printed a warning to logs if: 

* bcrypt hash generated with > 12 rounds is supplied for static user
* bcrypt comparison function ` CompareHashAndPassword()` taking longer than 10 seconds during a login

**Comment by rithujohn191** [comment]
Hi @colhom,

Could you please share the exact error message you saw during the timeout?

**Comment by colhom** [comment]
@rithujohn191 hello! There is no error message for this, the local connector will just take a very long time to verify a password. One way this problem pops up is the `/auth/local` POST request taking a very long time, possibly up to the point of causing an HTTP timeout.

**Comment by metral** [comment]
We're hitting ERR_EMPTY_RESPONSE errors as of 1409.x.0 (1409.2.0 & 1409.5.0) when trying to hit the console - the issue is tracked here: https://github.com/coreos/tectonic-installer/issues/1171

Reverting back to CL 1353.8.0 works for us consistently as long as we don't update, and ultimately https://github.com/coreos-inc/tectonic-issues/issues/258 led me here.

Thinking my brcrypt password cost was too high I made sure to create a new one with a cost of 10, but were still hitting the ERR_EMPTY_RESPONSE. I'm mainly dropping a note here to see if there's any ideas folks may have for next paths forward.

**Comment by ericchiang** [comment]
@metral I'm confused, why does the container linux version matter? dex doesn't interact with the OS in any way.

**Comment by metral** [comment]
Not necessarily saying it matters, just that it was the last remaining fault domain for us to test, and it ended up working when we reverted to 1353.8.0. I thought this issue was related to #1171 given https://github.com/coreos-inc/tectonic-issues/issues/258, but I suppose not.
